services:
  - type: web
    name: sih26038-backend-api
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=. uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
